FROM node:14-alpine as react-build
WORKDIR /app

COPY . ./
ARG REACT_APP_KAKAO_MAP_API_KEY
ENV REACT_APP_KAKAO_MAP_API_KEY=$REACT_APP_KAKAO_MAP_API_KEY
ARG REACT_APP_DOMAIN_API_URL
ENV REACT_APP_DOMAIN_API_URL=$REACT_APP_DOMAIN_API_URL
ARG REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_ALGOLIA_APP_ID
ENV REACT_APP_ALGOLIA_APP_ID=$REACT_APP_ALGOLIA_APP_ID
ARG REACT_APP_ALGOLIA_API_KEY
ENV REACT_APP_ALGOLIA_API_KEY=$REACT_APP_ALGOLIA_API_KEY
ARG REACT_APP_ALGOLIA_INDEX
ENV REACT_APP_ALGOLIA_INDEX=$REACT_APP_ALGOLIA_INDEX
RUN npm install
RUN npm run build

# server environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/configfile.template
ENV PORT 8080
ENV HOST 0.0.0.0
RUN sh -c "envsubst '\$PORT'  < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf"
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
